encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new, name="new"),
    path('random_page/', views.random_page, name="random_page"),
    path('search/', views.search, name="search"),
    path('<str:entry>/', views.entry, name="page"),
    path('<str:entry>/edit/', views.edit, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
2from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import util
import markdown2
import random


def index(request):
    """Lists all curent entries"""

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry(request, entry):
    """Renders markdown file in HTML page"""

    # Converts markdown file to string
    content = util.get_entry(entry)

    if content == None:
        return render(request, "encyclopedia/result.html", {
            "message": "Entry does not exist"
        })

    markdown_text = markdown2.markdown(content)

    return render(request, "encyclopedia/entry.html", {
        "entry": entry,
        "content": markdown_text
    })


def new(request):
    """Creates a new markdown file via an HTML form"""

    if request.method == "GET":
        return render(request, "encyclopedia/new.html")

    # when route is sent by POST
    elif request.method == "POST":

        #  Entry names
        form = request.POST
        title = form['title']
        content = form['content']

        entries = util.list_entries()

        print(title)
        print(entries)

        for item in entries:
            if title.lower() == item.lower():
                return render(request, "encyclopedia/result.html", {
                    "message": "Error! New entry was NOT added."
                })

        util.save_entry(title, content)
        return render(request, "encyclopedia/result.html", {
            "message": "Success! New entry added."
        })


def edit(request, entry):
    """Edit markdown file via HTML form"""

    if request.method == "GET":

        content = util.get_entry(entry)

        return render(request, "encyclopedia/edit.html", {
            "title": entry,
            "content": content,
        })

    elif request.method == "POST":

        form = request.POST
        title = form['title']
        content = form['content']

        util.save_entry(title, content)

        return HttpResponseRedirect(reverse("wiki:page", kwargs={'entry': title}))


def random_page(request):
    """Display random entry"""

    entries = util.list_entries()
    page = random.choice(entries)

    return HttpResponseRedirect(reverse("wiki:page", kwargs={'entry': page}))


def search(request):
    """Search for markdown file"""

    if request.method == "POST":
        # Get search term
        term = request.POST
        term = term['q']

        entries = util.list_entries()
        page = None

        # Check for match
        for item in entries:
            if term.lower() == item.lower():
                page = item
                print(f"Exact Match Found! -", page)

        if page != None:
            return HttpResponseRedirect(reverse("wiki:page", kwargs={'entry': page}))

        list = []
        for item in entries:
            if term.lower() in item.lower():
                list.append(item)

        if not list:
            return render(request, "encyclopedia/results.html")

        else:
            # Pass into results.html
            return render(request, "encyclopedia/results.html", {
                "results": list
            })


    else:
        return HttpResponse("Error")

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

<h1> Edit Page </h1>


<form method="post">

    <div class="form-group">
        <label for="title">Entry Title:</label>
        <input type="text" name="title" id="title" class="form-control" value={{title}} readonly>
    </div>

    <div class="form-group">
        <label for="content">Entry Content:</label>
        <textarea class="form-control" name="content" rows="15" id="content">{{content}}</textarea>
    </div>
    {% csrf_token %}
    <button class="btn btn-primary">Save</button>
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

<!-- Edit page -->
<a href='/{{entry}}/edit/' class="btn btn-primary" role="button"> Edit Page</a>

<h1>{{entry}}</h1>

{{ content | safe }}

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h1>All Pages</h1>

<ul>
    {% for entry in entries %}
    <li><a href="{{entry}}" </a>{{ entry }}</li>
    {% endfor %}
</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="row">

        <div class="sidebar col-lg-2 col-md-3">

            <img id="logo" src="/static/Wikipedia-logo-v2@2x.png" style="width: 150px">
            <h2 style="font-family: serif">Wiki George</h2>

            <form action="{% url 'wiki:search' %}" method="post">
                <input class="search" type="text" name="q" placeholder="Search Pages" type="submit">
                {% csrf_token %}
            </form>

            <div>
                <a href="{% url 'wiki:index' %}">&nbspHome</a>
            </div>
            <div>
                <a href="{% url 'wiki:new' %}">&nbspCreate New Page</a>
            </div>
            <div>
                <a href="{% url 'wiki:random_page' %}">&nbspRandom Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>

</body>

</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

<h1> New Page </h1>

<form action="{% url 'wiki:new' %}" method="post">
    <div class="form-group">
        <label for="title">Entry Title:</label>
        <input type="text" name="title" id="title" class="form-control">
    </div>
    <div class="form-group">
        <label for="content">Entry Content:</label>
        <textarea class="form-control" name="content" rows="15" id="content"></textarea>
    </div>
    {% csrf_token %}
    <button class="btn btn-primary">Submit</button>
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/result.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

<h3> {{ message }} </h3>

{% endblock %}

encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

<h1>Search Results</h1>

<ul>
    {% for page in results %}
    <li><a href="/{{page}}" </a>{{ page }}</li>
    {% empty %}
    <li> No results found. Click <a href="/"> here</a> and go back. </li>
    {% endfor %}
</ul>

{% endblock %}